### ISSUE TITLE
Unknown method 'country' for object Net::Whois::Object::Organisation (Did the Database schema changed ?)

### ISSUE THREAD

**Issue by moritz** [arhuman/Net-Whois-RIPE#28]
RIPE seems to have updated its database schema to include the filed `country` in the `organisation` object:
```
l$ perl -Ilib -MData::Dumper  -MNet::Whois::Object -MNet::Whois::RIPE -wE 'say for Net::Whois::Object->new( Net::Whois::RIPE->new->query("ORG-nnA1-RIPE"))'
Unknown method 'country' for object Net::Whois::Object::Organisation (Did the Database schema changed ?) at -e line 1.
Net::Whois::Object::Information=HASH(0x55b39beba518)
Net::Whois::Object::Information=HASH(0x55b39beba380)
Net::Whois::Object::Information=HASH(0x55b39b6cc7f8)
Net::Whois::Object::Organisation=HASH(0x55b39b6ccfa8)
Net::Whois::Object::Information=HASH(0x55b39bea6af8)
```

This happens on the current master (commit aa24dcb5d0c316e16152934df11d81d895332347, last tag was 2.007003) as well as on the released versions that I've tried.

This is how that object looks like (reduced to the interesting parts):

```
$ whois -h whois.ripe.net ORG-nnA1-RIPE|grep -A5 '^organisation:'
organisation:   ORG-nnA1-RIPE
org-name:       noris network AG
country:        DE
org-type:       LIR
address:        Thomas-Mann-Strasse 16-20
address:        90471
```

**Comment by arhuman** [comment]
Thanks for reporting.
I'll release shortly a new release to handle the multiple database changes.

**Comment by arhuman** [comment]
The code has been updated in release 2.008001

**Comment by moritz** [comment]
Thanks for the quick update @arhuman!

It seems you have forgotten to push the `2.008001` tag to github (at least I couldn't find it).

**Comment by arhuman** [comment]
Arghh...
One day I'll do a release without mistake ;-)
(fixed)
